### ISSUE TITLE
Updating to 1.0.3 gives errors on go 1.16

### ISSUE THREAD

**Issue by alex-broad** [cocoonspace/dynjson#19]
```
$ go get -u github.com/cocoonspace/dynjson
go get: github.com/cocoonspace/dynjson@v1.0.2 updating to
        github.com/cocoonspace/dynjson@v1.0.3: parsing go.mod:
        module declares its path as: pkgs/dynjson
                but was required as: github.com/cocoonspace/dynjson
$ go version
go version go1.16.6 linux/amd64
$
```

I see the `go.mod` file now has pkgs/dynjson - I haven't been able to get this to work using go 1.16. Do you have a way to make this work? Is this intended? I think we're blocked from consuming the fix upstream while our project is using 1.16 :/

**Comment by jfbus** [comment]
My bad. Sorry about that. I'll fix it ASAP.
